version: "3"

services:
    ubuntu:
        build:
            context: ubuntu
            args:
                - UBUNTU_VERSION=16.04
        environment:
            - VNC_PASSWORD=${VNC_PASSWORD}
        image: gnucash_novnc
        container_name: gnucash_novnc1
        volumes:
            - /mnt/nfs/svr1/documents:/mnt/nfs_svr1_documents
        ports:
            - "5901:5901"
            - "6901:6901"
